devicetree-org/devicetree-website

_assets/css/custom.scss

Background Fix for Homepage

---

_assets/css/custom.scss

Commenting out previous change as displaying incorrect on staging/production

---

_assets/css/custom.scss
contact/index.html
openfirmware-docs/1275/bindings/dna/dna0_2d-styled.html
openfirmware-docs/1275/bindings/dna/dna0_2d.html
openfirmware-docs/1275/bindings/postscript/index.html
openfirmware-docs/1275/practice/devicex/dse1_0a.html

Commented out broken links in openfirmware docs causing bamboo build to fail

---

_assets/css/custom.scss

Added background-position:center fix for homepage image

---

_assets/css/custom.scss
_data/footer.yml
thankyou/README.md

Updated footer link - sass for DeviceTree

---

faq/README.md
releases/README.md

Signed-off-by: Kanta Vekaria <kanta.vekaria@linaro.org>

Made two changes regarding planned releases

---

press/README.md

Updated blog link for press page

---

specifications/README.md

There are no current confirmed dates for releases so these are removed from the text
Signed-off-by: Kanta Vekaria <kanta.vekaria@linaro.org>

Update dates for planned releases

---

_data/redirects.csv

Added folder redirect for Device_Tree_Usage

---

index.md
releases/README.md
specifications/README.md

Include information about both the current v0.1 stable release, and
the pre-release draft for v0.2. Also start pointing at the GitHub
releases page for official document images.
Signed-off-by: Grant Likely <grant.likely@arm.com>

Update release information

---

_assets/css/custom.scss

Fix for tabbed nav bar colour issue

---

_assets/css/custom.scss

Fix for tabbed nav bar on mobile

---

index.md
releases/README.md

This kind of pull request is going to get tedious in a hurry. Really need to get dt.org to scrape the release details from github, but in the meantime here is an update to v0.2-rc1
Signed-off-by: Grant Likely <grant.likely@arm.com>

Update latest release to v0.2-rc1

---

_posts/2017-12-20-devicetree-specification-0.2-released.markdown
index.md
releases/README.md

Signed-off-by: Grant Likely <grant.likely@arm.com>

Update to v0.2 release

---

Gemfile
assets/css/core/fonts.scss

Updated theme version

---

Gemfile
_data/nav.yml
assets/css/app/custom.scss
assets/js/app/sticky-tab-bar.js
committee/README.md
governance/README.md
members/README.md
press/README.md
releases/README.md
specifications/README.md

- Added the universal navbar.
- removed sticky-tab-bar.html includes and used the layout instead.

Universal Nav added

---

assets/css/app/custom.scss

We are replacing the Cognito forms on our static websites with a simple contact button using a mailto: link and a prefilled subject line to automatically assign tickets which come in. This will allow us to track who is working on which ticket in the Service Desk portal.

Replaced the Cognito form with a static contact button.

---

Gemfile
assets/js/package-releases.js
assets/js/package-search.js

Updated JS packages - bumped to v3.1.0 of jumbo-jekyll-theme

Updated JS packages - bumped to v3.1.0 of jumbo-jekyll-theme

---

Gemfile
_data/universal-nav.yml

Added TrustedFirmware.org to the universal navbar

Added TrustedFirmware.org to the universal navbar

---

Gemfile
_data/nav.yml
_includes/thumbnail_image.html

Updated the jumbo-jekyll-theme version

Updated the jumbo-jekyll-theme version

---

open-firmware/practice/devicex/index.html
open-firmware/practice/devicex/indexDeqA.html
open-firmware/practice/devicex/indexDeqD.html
open-firmware/practice/devicex/indexMeqA.html
open-firmware/practice/devicex/indexMeqD.html
open-firmware/practice/devicex/indexNeqA.html
open-firmware/practice/devicex/indexNeqD.html
open-firmware/practice/devicex/indexSeqA.html
open-firmware/practice/devicex/indexSeqD.html

The static web site infrastructure cannot support filenames with ? and = in them so I've renamed the files and updated the HREFs to match.

Fix unsupported filenames

---

_data/settings.yml

Fixing analytics issue adding missing code

Fixing analytics issue

---

_data/universal-nav.yml
_pages/members/README.md

Added OpenAMP to universal nav

Added OpenAMP to universal nav

---

Gemfile
_data/settings.yml
_data/universal-nav.yml
_pages/members/README.md

Updating theme version to 5.6.5

Updating theme version to 5.6.5

---

_data/routingrules.json

Correcting invalid redirect rules

Correcting invalid redirect rules

---

_data/routingrules.json

Develop -> Master (fixing incorrect redirects)

Develop -> Master (fixing incorrect redirects)

---

Gemfile
robots.txt

Robots.txt fix

---

_pages/faq/README.md

Update the releases location

---

Gemfile
_config.yml

Upgrading theme version
